export enum Role_Enum {
    UMUFASHAMYUMVIRE = "UMUFASHAMYUMVIRE",
    AGRONOMIST = "AGRONOMIST",
    VETERINARIAN = "VETERINARIAN",
    FARMER = "FARMER",
    ADMIN = "ADMIN",
    BUTCHER = "BUTCHER",
    COOPERATIVE_MANAGER = "COOPERATIVE_MANAGER"
}