export enum Role_Enum {
    UMUFASHAMYUMVIRE = "UMUFASHAMYUMVIRE",
    AGRONOMIST = "AGRONOMIST",
    VETERINARIAN = "VETERINARIAN",
    FARMER = "FARMER",
    ADMIN = "ADMIN",
    BUTCHER = "BUTCHER",
    COLLECTIVE_COOPERATIVE_MANAGER = "COLLECTIVE_COOPERATIVE_MANAGER",
    NON_COLLECTIVE_COOPERATIVE_MANAGER = "NON_COLLECTIVE_COOPERATIVE_MANAGER",
    DEV_ADMIN = "DEV_ADMIN",
    BUYER = "BUYER"
}